[package]
name = "create-task"
authors = ["Gavin Noktes <gnoktes@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-std = "1.11.0"
web-sys = { version = "0.3.57", features = ["Document", "HtmlElement", "Window"] }
